package mapred;

public enum Counters {
	HOMOGENEOUS_COLUMNS,
	CUTOFF,
	PRUNE,
	EMPTY_COLUMNS,
	SINGLE_COLUMN_NOT_ONE,
	ATTRACTORS,
	MATRIX_SLICES,
	MAP_INPUT_VALUES,
	MAP_OUTPUT_VALUES,
	DIAG_MASS,
	NON_DIAG_MASS,
	COMBINE_INPUT_VALUES,
	COMBINE_OUTPUT_VALUES,
	REDUCE_INPUT_VALUES,
	REDUCE_OUTPUT_VALUES,
	MAP_CPU_MICROS,
	REDUCE_CPU_MICROS,
	COMBINE_CPU_MICROS
}