package mapred;

/**
 * counters used in the MapReduce jobs
 * 
 * @author Cedrik
 *
 */
public enum Counters {
	HOMOGENEOUS_COLUMNS,
	CUTOFF,
	PRUNE,
	EMPTY_COLUMNS,
	SINGLE_COLUMN_NOT_ONE,
	ATTRACTORS,
	MATRIX_SLICES,
	MAP_INPUT_VALUES,
	MAP_OUTPUT_VALUES,
	DIAG_MASS,
	NON_DIAG_MASS,
	COMBINE_INPUT_VALUES,
	COMBINE_OUTPUT_VALUES,
	REDUCE_INPUT_VALUES,
	REDUCE_OUTPUT_VALUES,
	MAP_CPU_MILLIS,
	REDUCE_CPU_MILLIS,
	COMBINE_CPU_MILLIS,
	MAP_INPUT_SLICES,
	MAP_INPUT_BLOCKS,
	MAP_INPUT_BLOCK_VALUES,
	SLICE_WITHOUT_BLOCKS, NULL_BLOCKS, MAP_OUTPUT_BLOCKS
}