/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_test_NativeTest */

#ifndef _Included_io_test_NativeTest
#define _Included_io_test_NativeTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_test_NativeTest
 * Method:    hello
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_test_NativeTest_hello
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
